version: '3.8'

services:
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
    networks:
      my_network:
        ipv4_address: 172.28.0.3
    privileged: true

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      my_network:
        ipv4_address: 172.28.0.4

  python:
    build:
      context: ./Scrapper
      dockerfile: Dockerfile
    depends_on:
      chrome:
        condition: service_healthy
    networks:
      my_network:
        ipv4_address: 172.28.0.2
    links: 
        - chrome
    
  spring:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    depends_on:
      chrome:
        condition: service_healthy
    networks:
      my_network:
        ipv4_address: 172.28.0.5
    links: 
        - chrome
networks:
  my_network:
    ipam:
      config:
        - subnet: 172.28.0.0/16